repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
    - id: detect-secrets
      # args: ['--baseline', '.secrets.baseline']
      exclude: README.md

- repo: local
  hooks:
  - id: shellcheck
    name: shellcheck-pre-commit-hook
    entry: githooks/shellcheck-pre-commit.sh
    language: script
